package agent

import (
	"context"
	"crypto/rand"
	_ "embed"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/zendev-sh/goai"
	"github.com/zendev-sh/goai/provider"
	"github.com/zendev-sh/goai/provider/anthropic"
	"github.com/zendev-sh/goai/provider/compat"
	"github.com/zendev-sh/goai/provider/google"
	"github.com/zendev-sh/goai/provider/ollama"

	"github.com/aleksanaa/hyphae/internal/session"
	starlark "github.com/aleksanaa/hyphae/internal/third_party/starlark/starlark"
)

//go:embed plan_mode.md
var planModePrompt string

// systemPrompt is the base system message, authored in system_prompt.md. The
// embedded file's trailing newline is trimmed once at startup so the message
// stays clean when systemExtra is appended.
//
//go:embed system_prompt.md
var systemPromptRaw string

var systemPrompt = strings.TrimSpace(systemPromptRaw)

// systemExtra is appended to systemPrompt for every session's system message. It
// holds the global user instructions and the available-skills index, assembled
// once at startup by SetSystemContext. Empty until then, so absent config files
// leave the system prompt byte-identical to the base const.
var systemExtra string

// SetSystemContext assembles the per-process system-prompt suffix from the global
// user instructions and the discovered skills. Call once at startup, before any
// turn runs.
func SetSystemContext(globalInstructions string, skills []Skill) {
	var b strings.Builder
	if s := strings.TrimSpace(globalInstructions); s != "" {
		b.WriteString("\n\nThe user has provided global instructions that apply to every session. Follow them.\n")
		b.WriteString("<user_instructions>\n")
		b.WriteString(s)
		b.WriteString("\n</user_instructions>")
	}
	b.WriteString(FormatSkills(skills))
	systemExtra = b.String()
}

// EventType classifies an agent event sent to the UI.
type EventType string

const (
	EventTextDelta      EventType = "text_delta"      // partial assistant text
	EventReasoningDelta EventType = "reasoning_delta" // partial reasoning/thinking content
	EventToolStart      EventType = "tool_start"      // tool call beginning
	EventToolDone       EventType = "tool_done"       // tool call finished
	EventDone           EventType = "done"            // turn complete
	EventError          EventType = "error"           // unrecoverable error
	EventToolApproval   EventType = "tool_approval"   // waiting for user approval
	EventSelectPrompt   EventType = "select_prompt"   // waiting for user selection (ask_user tool)
	EventConnecting     EventType = "connecting"      // establishing connection (may be retrying)
	EventPreparingTool  EventType = "preparing_tool"  // tool calls received, about to execute
	EventUsageUpdate    EventType = "usage_update"    // prompt token count updated after each LLM call
	EventStatusUpdate   EventType = "status_update"   // structured tool operation update (doing/wants/done)
)

const maxConnectAttempts = 3

// ApprovalResult is the user's response to an approval request.
type ApprovalResult struct {
	Allowed    bool
	DenyReason string
}

// ToolEvent carries info about a single tool invocation.
type ToolEvent struct {
	CallID    string
	Name      string
	Args      map[string]any // structured arguments of a call awaiting approval (reasoning excluded)
	Reasoning string
	Output    string // filled in on EventToolDone
	IsError   bool
	// Set for write_file and edit_file before approval.
	FilePath  string // relative path of file being changed
	DiffPatch string // unified diff of the pending change
	// Set for ask_user before EventSelectPrompt.
	SelectQuestion string
	SelectOptions  []string
}

// Event is one item from the agent event stream.
type Event struct {
	Type         EventType
	Text         string // EventTextDelta
	Tool         *ToolEvent
	Err          error               // EventError
	RespCh       chan ApprovalResult // EventToolApproval only; send exactly once
	SelectRespCh chan string         // EventSelectPrompt only; send exactly once
	// EventConnecting fields:
	Attempt     int           // current attempt number (1-based)
	MaxAttempts int           // total allowed attempts
	RetryAfter  time.Duration // >0 means waiting before the next attempt
	// EventUsageUpdate / EventDone fields:
	PromptTokens     int64 // tokens in the prompt for this LLM call (from API)
	CompletionTokens int64 // tokens generated by the model for this LLM call
	// EventToolStart: index of the tool status message the controller records
	// this call's structured status events against.
	// EventStatusUpdate: one structured tool operation update (doing/wants/done).
	StatusMsgIdx int
	StatusEvent  session.StatusEvent
}

// Agent orchestrates the LLM ↔ tool loop. Each agent serves a single session,
// so the run-tool namespace (persistent starlark globals) is a plain field.
type Agent struct {
	model     provider.LanguageModel
	namespace starlark.StringDict
	grants    *grantSet // access granted at runtime via request_access; per-session

	// genOpts are provider-specific request options passed on every generation
	// (e.g. Ollama's "think" to surface reasoning). nil for providers that need none.
	genOpts map[string]any

	// Transport config retained for the direct /models listing, which goai
	// does not provide.
	providerType string
	baseURL      string
	apiKey       string
	modelID      string
}

// New creates an Agent for the given provider type ("openai"/"" for a generic
// OpenAI-compatible endpoint, "anthropic", "google", or "ollama"), base URL, API
// key, and model ID.
func New(providerType, baseURL, apiKey, model string) *Agent {
	return &Agent{
		model:        buildModel(providerType, baseURL, apiKey, model),
		namespace:    make(starlark.StringDict),
		grants:       newGrantSet(),
		genOpts:      genOptsFor(providerType),
		providerType: providerType,
		baseURL:      baseURL,
		apiKey:       apiKey,
		modelID:      model,
	}
}

// genOptsFor returns the provider-specific generation options for a provider type.
// Ollama only returns reasoning when "think" is set, so enable it there; the loop
// drops it if the chosen model reports no thinking support.
func genOptsFor(providerType string) map[string]any {
	if providerType == "ollama" {
		return map[string]any{"think": true}
	}
	return nil
}

// buildModel selects the goai provider for the endpoint type. WithBaseURL is
// only applied when a URL is supplied, so the native providers fall back to
// their default hosts when the endpoint leaves it blank.
func buildModel(providerType, baseURL, apiKey, model string) provider.LanguageModel {
	switch providerType {
	case "anthropic":
		opts := []anthropic.Option{anthropic.WithAPIKey(apiKey)}
		if baseURL != "" {
			opts = append(opts, anthropic.WithBaseURL(baseURL))
		}
		return anthropic.Chat(model, opts...)
	case "google":
		opts := []google.Option{google.WithAPIKey(apiKey)}
		if baseURL != "" {
			opts = append(opts, google.WithBaseURL(baseURL))
		}
		return google.Chat(model, opts...)
	case "ollama":
		// Ollama is local and unauthenticated (no API key); it defaults to
		// http://localhost:11434 when no base URL is supplied.
		var opts []ollama.Option
		if baseURL != "" {
			opts = append(opts, ollama.WithBaseURL(baseURL))
		}
		return ollama.Chat(model, opts...)
	default: // "openai" or ""
		return compat.Chat(model, compat.WithBaseURL(baseURL), compat.WithAPIKey(apiKey))
	}
}

// Grants returns the session's user grants (excluding the pre-registered
// builtins), for persistence and the palette.
func (a *Agent) Grants() []Grant { return a.grants.list() }

// AllGrants returns every permission the session holds, including the
// pre-registered builtins (working directory and skills directory), for display
// to the model.
func (a *Agent) AllGrants() []Grant { return a.grants.listAll() }

// LoadGrants replaces the session's grants, e.g. when resuming from storage.
func (a *Agent) LoadGrants(grants []Grant) { a.grants.load(grants) }

// AddGrant records a grant requested directly by the user (e.g. via the palette),
// normalizing the target the same way request_access does. kind is "readonly",
// "readwrite", or "web_fetch"; workDir anchors relative directory targets. It
// returns the normalized scope that was stored.
func (a *Agent) AddGrant(kind, target, workDir string) string {
	return a.grants.grant(kind, target, workDir)
}

// RevokeGrant removes one grant matching g exactly, reporting whether it existed.
func (a *Agent) RevokeGrant(g Grant) bool { return a.grants.revoke(g) }

// Send starts the agent loop from the current session state.
// The caller must have already added the user message to the session.
// Returns a channel of events; closed when the turn is complete or errored.
func (a *Agent) Send(ctx context.Context, sess *session.Session) <-chan Event {
	ch := make(chan Event, 64)
	go func() {
		defer close(ch)
		a.loop(ctx, sess, ch)
	}()
	return ch
}

func (a *Agent) loop(ctx context.Context, sess *session.Session, ch chan<- Event) {
	tools := schemas()

	for {
		if ctx.Err() != nil {
			return
		}

		system, msgs := buildMessages(sess)

		// Each streamed response splits into peer items: reasoning flows into a
		// lazily-created RoleThinking status; text into a RoleAssistant message.
		// Both are created only if their content actually arrives.
		thinkingIdx, assistantIdx := -1, -1
		var thinkStart time.Time
		thinkFinalized := false
		// settleThinking freezes the thinking status the moment reasoning ends
		// (when text or tools begin) so it stays visible instead of lingering as
		// an in-progress item hidden behind the streaming answer.
		settleThinking := func() {
			if thinkingIdx >= 0 && !thinkFinalized {
				sess.FinalizeThinking(thinkingIdx, int(time.Since(thinkStart).Seconds()))
				thinkFinalized = true
			}
		}

		var streamErr error
		var content string
		var toolCalls []provider.ToolCall
		var usage provider.Usage
		genOpts := a.genOpts // dropped below if the model rejects a request option (e.g. Ollama think)
		for attempt := 1; attempt <= maxConnectAttempts; attempt++ {
			select {
			case ch <- Event{Type: EventConnecting, Attempt: attempt, MaxAttempts: maxConnectAttempts}:
			case <-ctx.Done():
				return
			}

			// Reset per-attempt accumulators; a retry only happens when nothing
			// streamed (gotChunk stays false), so these never carry partial state.
			content = ""
			toolCalls = nil
			usage = provider.Usage{}
			streamErr = nil
			gotChunk := false
			toolIndex := map[string]int{} // dedupe streamed tool calls by ID, keep order

			res, err := a.model.DoStream(ctx, provider.GenerateParams{
				System:          system,
				Messages:        msgs,
				Tools:           tools,
				ProviderOptions: genOpts,
			})
			if err != nil {
				// Ollama rejects think=true on models without thinking support;
				// drop the option and retry the same step rather than fail.
				if genOpts["think"] == true && thinkingUnsupported(err) {
					genOpts = nil
					attempt--
					continue
				}
				streamErr = err
			} else {
				for chunk := range res.Stream {
					gotChunk = true
					switch chunk.Type {
					case provider.ChunkReasoning:
						if chunk.Text == "" {
							continue
						}
						if thinkingIdx < 0 {
							thinkingIdx = sess.AddMessage(session.Message{Role: session.RoleThinking, Partial: true})
							thinkStart = time.Now()
						}
						sess.AppendThinkingDelta(thinkingIdx, chunk.Text)
						select {
						case ch <- Event{Type: EventReasoningDelta, Text: chunk.Text}:
						case <-ctx.Done():
						}
					case provider.ChunkText:
						if chunk.Text == "" {
							continue
						}
						if assistantIdx < 0 {
							settleThinking() // text ends the thinking phase
							assistantIdx = sess.AddMessage(session.Message{Role: session.RoleAssistant, Partial: true})
						}
						content += chunk.Text
						sess.AppendTextDelta(assistantIdx, chunk.Text)
						select {
						case ch <- Event{Type: EventTextDelta, Text: chunk.Text}:
						case <-ctx.Done():
						}
					case provider.ChunkToolCall:
						if chunk.ToolCallID == "" {
							// Ollama (and other native providers) don't issue tool-call
							// IDs; each ChunkToolCall is a complete, distinct call. Give
							// it a synthesized unique ID so it persists under its own
							// call_id (the store's tool_calls.call_id is UNIQUE) and can
							// be matched on resume; without one, every call after the
							// first collides and is dropped on reload.
							toolCalls = append(toolCalls, provider.ToolCall{
								ID:    newToolCallID(),
								Name:  chunk.ToolName,
								Input: []byte(chunk.ToolInput),
							})
							break
						}
						// The compat provider emits a complete ChunkToolCall (full
						// JSON args) once accumulated; index by ID so a repeat for the
						// same call overwrites rather than duplicates.
						if idx, ok := toolIndex[chunk.ToolCallID]; ok {
							toolCalls[idx].Name = chunk.ToolName
							toolCalls[idx].Input = []byte(chunk.ToolInput)
						} else {
							toolIndex[chunk.ToolCallID] = len(toolCalls)
							toolCalls = append(toolCalls, provider.ToolCall{
								ID:    chunk.ToolCallID,
								Name:  chunk.ToolName,
								Input: []byte(chunk.ToolInput),
							})
						}
					case provider.ChunkFinish:
						usage = chunk.Usage
					case provider.ChunkError:
						if chunk.Error != nil {
							streamErr = chunk.Error
						}
					}
				}
			}

			// Stop retrying on success, context cancellation, or once anything
			// streamed (mid-stream failures are not resumable).
			if streamErr == nil || !isRetryable(streamErr) || gotChunk {
				break
			}
			if attempt < maxConnectAttempts {
				delay := time.Duration(1<<attempt) * time.Second // 2s, 4s
				select {
				case ch <- Event{Type: EventConnecting, Attempt: attempt, MaxAttempts: maxConnectAttempts, RetryAfter: delay, Err: streamErr}:
				case <-ctx.Done():
					return
				}
				select {
				case <-time.After(delay):
				case <-ctx.Done():
					return
				}
			}
		}

		// Settle thinking for tool-only rounds where no text arrived to trigger it.
		settleThinking()

		if streamErr != nil {
			if assistantIdx < 0 {
				assistantIdx = sess.AddMessage(session.Message{Role: session.RoleAssistant})
			}
			sess.SetMessageError(assistantIdx, streamErr)
			select {
			case ch <- Event{Type: EventError, Err: streamErr}:
			default:
			}
			return
		}

		// Settle the assistant message with the full streamed text.
		if content != "" && assistantIdx < 0 {
			assistantIdx = sess.AddMessage(session.Message{Role: session.RoleAssistant, Partial: true})
		}
		if assistantIdx >= 0 {
			sess.FinalizeMessage(assistantIdx, content)
		}

		// Emit usage after every LLM call so the status bar updates during tool
		// loops. goai normalizes InputTokens to exclude cache-read tokens; add
		// them back so the prompt count reflects the full context sent.
		if pt := int64(usage.InputTokens + usage.CacheReadTokens); pt > 0 {
			select {
			case ch <- Event{Type: EventUsageUpdate, PromptTokens: pt, CompletionTokens: int64(usage.OutputTokens)}:
			case <-ctx.Done():
				return
			}
		}

		if len(toolCalls) == 0 {
			ch <- Event{Type: EventDone}
			return
		}

		select {
		case ch <- Event{Type: EventPreparingTool}:
		case <-ctx.Done():
			return
		}

		for _, tc := range toolCalls {
			if ctx.Err() != nil {
				return
			}

			args := string(tc.Input)
			te := &ToolEvent{CallID: tc.ID, Name: tc.Name}

			// One tool status item per call; its index is where the controller
			// records this call's structured status events.
			toolIdx := sess.AddMessage(session.Message{
				Role: session.RoleTool,
				ToolUses: []session.ToolUse{{
					ID: tc.ID, Name: tc.Name, Input: args, State: "running",
				}},
			})

			select {
			case ch <- Event{Type: EventToolStart, Tool: te, StatusMsgIdx: toolIdx}:
			case <-ctx.Done():
				return
			}

			output, isErr, anyToolsRan := runScript(ctx, ch, args, sess.WorkDir, a.namespace, a.grants)
			te.Output = output
			te.IsError = isErr
			if !anyToolsRan {
				var fallback session.StatusEvent
				if isErr {
					fallback = session.StatusEvent{Kind: session.StatusEventFailed, Verb: "run", NounP: "functions", Target: "1 function"}
				} else {
					fallback = session.StatusEvent{Kind: session.StatusEventDone, Verb: "ran", NounP: "functions", Target: "1 function"}
				}
				select {
				case ch <- Event{Type: EventStatusUpdate, StatusEvent: fallback}:
				case <-ctx.Done():
				}
			}

			sess.SetToolResult(toolIdx, tc.ID, output, isErr)

			select {
			case ch <- Event{Type: EventToolDone, Tool: te}:
			case <-ctx.Done():
				return
			}
		}

		// A tool round always continues to the model's next step, whether or not it
		// came with preamble text. The turn ends only when a response carries no
		// tool calls (handled above). Items stay in natural occurrence order.
	}
}

// buildMessages returns the system prompt (a GenerateParams field, not a leading
// message) and the conversation messages for the current session state.
func buildMessages(sess *session.Session) (string, []provider.Message) {
	var msgs []provider.Message

	summary, compactSeqs := sess.GetCompact()
	startIdx := 0
	if len(compactSeqs) > 0 {
		startIdx = compactSeqs[len(compactSeqs)-1] + 1
	}
	if summary != "" {
		msgs = append(msgs,
			goai.UserMessage("[Previous conversation summary]\n\n"+summary),
			goai.AssistantMessage("Understood. I'll continue from where we left off."),
		)
	}

	history, _ := sess.Snapshot()
	msgs, _ = appendHistory(msgs, history, startIdx)
	return systemPrompt + systemExtra, msgs
}

// FormatSentLabel returns the timestamp tag for a user message.
func FormatSentLabel(t time.Time) string {
	_, secs := t.Local().Zone()
	h, mins := secs/3600, secs%3600/60
	if mins < 0 {
		mins = -mins
	}
	var tz string
	if mins != 0 {
		tz = fmt.Sprintf("UTC%+d:%02d", h, mins)
	} else {
		tz = fmt.Sprintf("UTC%+d", h)
	}
	return "<system-timestamp>The message is sent on " + t.Local().Format("2006-01-02 15:04") + " " + tz + "</system-timestamp>"
}

// SystemReminder wraps body in the <system-reminder> tags used to attach
// out-of-band context (plan mode, resume notices, working-directory changes, …)
// to the next user message. All such notices go through this so their framing
// stays consistent.
func SystemReminder(body string) string {
	return "<system-reminder>\n" + body + "\n</system-reminder>"
}

// PlanModeLabel returns the system-reminder block to append for an active plan mode turn.
func PlanModeLabel() string {
	return SystemReminder(planModePrompt)
}

// PlanModeExitLabel returns the system-reminder block to append when plan mode just ended.
func PlanModeExitLabel() string {
	return SystemReminder("Plan mode has ended. You may now make changes freely.")
}

// WorkDirChangedLabel returns the system-reminder block announcing that the
// session's working directory moved from one path to another.
func WorkDirChangedLabel(from, to string) string {
	return SystemReminder(fmt.Sprintf(
		"The working directory has changed from %s to %s. This session was resumed in a "+
			"different location than where it originally ran, so relative file paths and shell "+
			"commands now resolve against the new directory. Files, directories, and paths "+
			"referenced earlier in the conversation may no longer exist at their previous "+
			"locations, may have different contents, or may be absent entirely here. Do not "+
			"assume anything from the earlier working directory is present — verify paths (e.g. "+
			"by listing or reading them) before acting on them.",
		from, to))
}

// NamespaceClearedLabel returns the system-reminder block injected on cold session resume.
func NamespaceClearedLabel() string {
	return SystemReminder("This session was resumed from storage. The run namespace has been reset — any variables or functions defined in previous run calls are no longer available.")
}

// newToolCallID returns a unique tool-call ID for providers that don't supply
// one (e.g. Ollama). The "call_" prefix mirrors the OpenAI-style IDs the rest of
// the pipeline expects; the random suffix keeps it unique against the store's
// UNIQUE call_id constraint.
func newToolCallID() string {
	var b [12]byte
	if _, err := rand.Read(b[:]); err != nil {
		return fmt.Sprintf("call_%d", time.Now().UnixNano())
	}
	return "call_" + hex.EncodeToString(b[:])
}

// thinkingUnsupported reports whether err indicates the model rejected the
// "think" request option, which Ollama returns for models without thinking
// support. Matched loosely on the message since goai surfaces it as a plain
// API error string.
func thinkingUnsupported(err error) bool {
	if err == nil {
		return false
	}
	msg := strings.ToLower(err.Error())
	return strings.Contains(msg, "think") && strings.Contains(msg, "support")
}

// isRetryable returns true for transient errors that warrant a retry.
// Context cancellation and deadline are not retried.
func isRetryable(err error) bool {
	return err != nil &&
		!errors.Is(err, context.Canceled) &&
		!errors.Is(err, context.DeadlineExceeded)
}
